# Generated by Django 2.2.1 on 2019-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_plan',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('choosen_plan', models.IntegerField()),
            ],
        ),
    ]
